[package]
name = "day04"
version = "0.1.0"
authors = ["Michael Mario Kubicki <contact@michael-kubicki.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
common = { path = "../common" }
anyhow = "1.0"
thiserror = "1.0"
